import mongoose from 'mongoose';

const base = { timestamps: true };
export const User = mongoose.model('User', new mongoose.Schema({ name:{type:String,required:true,minlength:2,maxlength:60}, email:{type:String,required:true,unique:true,lowercase:true}, role:{type:String,enum:['fan','admin'],default:'fan'} },base));
export const Cinema = mongoose.model('Cinema', new mongoose.Schema({ name:{type:String,required:true}, branch:{type:String,required:true}, city:{type:String,required:true}, address:{type:String,required:true}, capacity:{type:Number,min:1,required:true} },base));
export const Showtime = mongoose.model('Showtime', new mongoose.Schema({ cinemaId:{type:mongoose.Schema.Types.ObjectId,ref:'Cinema',required:true}, movieTitle:{type:String,required:true}, date:{type:Date,required:true}, time:{type:String,required:true}, capacity:{type:Number,min:1,required:true}, ticketPrice:{type:Number,min:0,required:true} },base));
export const Booking = mongoose.model('Booking', new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}, showtimeId:{type:mongoose.Schema.Types.ObjectId,ref:'Showtime',required:true}, seatCount:{type:Number,min:1,max:10,required:true}, status:{type:String,enum:['confirmed','cancelled','expired','completed'],default:'confirmed'}, expiresAt:{type:Date,required:true} },base));
export const Merchandise = mongoose.model('Merchandise', new mongoose.Schema({ name:{type:String,required:true,minlength:2}, category:{type:String,required:true}, price:{type:Number,min:0,required:true}, stock:{type:Number,min:0,required:true}, discountPercent:{type:Number,min:0,max:100,default:0}, discountExpiresAt:{type:Date} },base));
export const Order = mongoose.model('Order', new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}, items:[{merchandiseId:{type:mongoose.Schema.Types.ObjectId,ref:'Merchandise',required:true},quantity:{type:Number,min:1,required:true}}], subtotal:{type:Number,min:0,required:true}, discount:{type:Number,min:0,required:true}, fee:{type:Number,min:0,required:true}, total:{type:Number,min:0,required:true}, status:{type:String,enum:['pending','confirmed','cancelled'],default:'confirmed'} },base));
export const Character = mongoose.model('Character', new mongoose.Schema({ name:{type:String,required:true,unique:true}, comicRole:{type:String,required:true}, description:{type:String,required:true} },base));
export const Submission = mongoose.model('Submission', new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}, title:{type:String,required:true,minlength:5,maxlength:120}, content:{type:String,required:true,minlength:10,maxlength:2000}, category:{type:String,enum:['theory','comic-possibility','casting','screen-time'],required:true}, status:{type:String,enum:['pending','approved','rejected','published'],default:'pending'}, votes:{type:Number,min:0,default:0} },base));
export const Prediction = mongoose.model('Prediction', new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}, characterId:{type:mongoose.Schema.Types.ObjectId,ref:'Character',required:true}, predictedScreenTime:{type:Number,min:0,max:300,required:true}, storyline:{type:String,required:true} },base));
